# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    # Project coverage (overall codebase)
    project:
      default:
        target: auto
        threshold: 5%  # Allow up to 5% drop in total coverage
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false
    
    # Patch coverage (new code in PR)
    patch:
      default:
        target: 80%  # New code should have at least 85% coverage
        threshold: 5%  # Allow some flexibility for edge cases
        base: auto
        if_ci_failed: error
        informational: true
        only_pulls: true

# Ignore certain files/directories from coverage
ignore:
  - "node_modules/**/*"
  - "examples/**/*"
  - "dist/**/*"
  - "*.md"
  - ".github/**/*"
  - ".ai/**/*"
  - "wiki/**/*"

# Comment configuration
comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - master
    - develop

# GitHub Checks configuration
github_checks:
  annotations: true

# Notification settings (optional)
# comment: false  # Uncomment to disable PR comments